# Generated by Django 3.2.9 on 2023-05-17 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_ticket_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='time_created',
        ),
    ]
