# Generated by Django 3.2.9 on 2023-05-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ticket',
        ),
    ]
