# Generated by Django 3.2.9 on 2023-05-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_review_user_alter_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=128, verbose_name='title'),
        ),
    ]
