# Generated by Django 3.2.9 on 2023-05-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userfollows'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='authentication.User'),
        ),
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
