# Generated by Django 3.2.9 on 2023-05-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20230522_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='default.png', upload_to='profile_pics/'),
        ),
    ]
