# Generated by Django 3.2.9 on 2023-05-23 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20230523_0107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
