# Generated by Django 3.2.9 on 2023-05-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_userfollow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_authentication_profile_followers_+', to='authentication.Profile'),
        ),
    ]
