# Generated by Django 3.2.9 on 2023-05-24 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_auto_20230524_2350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
