# Generated by Django 3.2.9 on 2023-05-25 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_profile_follows'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollow',
        ),
    ]
