# Generated by Django 3.2.9 on 2023-05-25 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_delete_userfollow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follows',
        ),
    ]
