# Generated by Django 3.2.9 on 2023-05-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_remove_profile_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(to='authentication.Profile', verbose_name='suit'),
        ),
    ]
