# Generated by Django 3.2.9 on 2023-05-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_alter_profile_follows'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayUsername',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
