# Generated by Django 3.2.9 on 2023-05-25 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_displayusername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displayusername',
            name='username',
        ),
    ]
