# Generated by Django 3.2.9 on 2023-05-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_remove_displayusername_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayUsernameu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='DisplayUsername',
        ),
    ]
