# Generated by Django 3.2.9 on 2023-05-25 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_auto_20230525_1102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisplayUsernameu',
        ),
    ]
