# Generated by Django 3.2.9 on 2023-05-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0035_profile_follows'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
