# Generated by Django 3.2.9 on 2023-06-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0036_delete_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_modified',
        ),
    ]
